//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GTL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Address
    {
        public int AddressID { get; set; }
        public string Zip { get; set; }
        public string City { get; set; }
        public string StreetName { get; set; }
        public string StreetNr { get; set; }
        public int FloorNr { get; set; }
        public string AptNr { get; set; }
        public string PhoneNr { get; set; }
    }
}
