//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GTL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Librarian
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Librarian()
        {
            this.Loans = new HashSet<Loan>();
        }
    
        public int SSN { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string LibrarianRole { get; set; }
        public System.DateTime DateHired { get; set; }
    
        public virtual LibrarianRole LibrarianRole1 { get; set; }
        public virtual Member Member { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Loan> Loans { get; set; }
    }
}
