//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GTL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Loan : IModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Loan()
        {
            this.LoanBooks = new HashSet<LoanBook>();
        }
    
        public int ID { get; set; }
        public int LibrarianID { get; set; }
        public int MemberID { get; set; }
        public System.DateTime DateCreated { get; set; }
    
        public virtual Librarian Librarian { get; set; }
        public virtual Member Member { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LoanBook> LoanBooks { get; set; }
    }
}
