//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GTL.Models
{
    using System;
    using System.Collections.Generic;
    using GTL.Interfaces;
    
    public partial class Member : IModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Member()
        {
            this.LibraryCards = new HashSet<LibraryCard>();
            this.Loans = new HashSet<Loan>();
            this.Notices = new HashSet<Notice>();
        }
    
        public int SSN { get; set; }
        public string MobilePhoneNr { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public int CampusAddressID { get; set; }
        public int HomeAddressID { get; set; }
        public bool IsActive { get; set; }
        public string Type { get; set; }
        public System.DateTime DateCreated { get; set; }

        public virtual Librarian Librarian { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LibraryCard> LibraryCards { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Loan> Loans { get; set; }
        public virtual MemberType MemberType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Notice> Notices { get; set; }


        public Address CampusAdress { get; set; }
        public Address HomeAddress { get; set; }

        public System.Reflection.PropertyInfo[] GetInfoProperties()
        {
            return this.GetType().GetProperties();
        }
    }
}
