Drop table LibrarianRolePermission
Drop table [Permission]
Drop table ForeignAcqusitionApplication
Drop table ForeignLibrary
Drop table BookWish
Drop table LibraryCardNotice
Drop table BookNotice
Drop table Notice
Drop table AuthorTitle
Drop table Author
Drop table LoanBook
Drop table Book
Drop table Title
Drop table LibraryCard
Drop table Loan
Drop table Librarian
Drop table LibrarianRole
Drop table Member
Drop table MemberType
Drop table [Address]
